// <auto-generated />
using System;
using Contexts.Membership.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contexts.Membership.Data.Migrations
{
    [DbContext(typeof(MembershipDbContext))]
    [Migration("20181216224125_membership-initial")]
    partial class membershipinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartSAR.BC.Membership.Domain.Aggregates.Person", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<Guid>("Id");

                    b.Property<string>("LastName");

                    b.HasKey("_id");

                    b.ToTable("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
